### ISSUE TITLE
Rate limiting / checking links mulitple times because they appear on multiple pages

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#4]
The server, that I am using to run broken_link_finder is quite limited in resources as it only has 1 CPU. I have noticed  that the 1 minute and 5 minute CPU load averages will go above 2 while broken_link_finder is running.

I know that I can use `nice` to slow processes down but I am also concerned that sites maybe dropping or refusing request because of too many in too short a time span. 

In my most recent test in the footer of one site there is a link to the site's Facebook page and to their Youtube channel. Both of these have been reported once in a reports on only one page that they were broken links. I used a web browser and `curl -I example.com` to check them and I was getting a HTTP response code of 200 for both.

Does broken_link_finder just go through found links on a page even if they exactly match ones that it has found on other pages on that site? If it is not passing over exact matching links that means for this site it would hit Youtube and Facebook on every page to test the same links.

**Comment by michaeltelford** [comment]
Thanks for raising the issue @frederickjh. The issue described here is that certain websites are dropping requests because they're being 'hit' with too many requests in a short space of time.

Yes, currently `broken_link_finder` simply crawls whatever links it finds and reports their status. I've been wanting to add some link recording logic for some time. Doing so will reduce the overall crawl times and required bandwidth. This will also aid the possibility of sites dropping requests because they believe they're being hit with a DOS attack. 

However, if a webpage has 50 links to Facebook, for example, all of them with different paths (making them unique from each other) then Facebook will likely continue to drop requests, so this isn't a full-proof solution to that problem. But given the small likely hood of such a scenario occurring, a full solution to this is way down the road map, if at all; especially when third party solutions to this exist i.e. `nice` as you suggested.

Since the efficiency of `broken_link_finder` is and always will be a priority, the next release will contain a form of link recording logic meaning each link on a page/site will only be crawled once. This will speed up the crawl for large sites (especially those with repeated links) and should somewhat help prevent dropped requests resulting in reported broken links.  I believe this will fix the issue you're seeing @frederickjh. I will update this issue when the release is out.

**Comment by michaeltelford** [comment]
OK, `broken_link_finder 0.8.1` should resolve the issues raised above. Here are the details for this version from the `CHANGELOG`:

## v0.8.1
### Added
- Logic to prevent re-crawling links for more efficiency. Users should see a substantial speed boost when crawling large sites with repeated links. This should also somewhat help prevent servers from dropping requests due to suspected DOS attacks.
### Changed/Removed
- Updated the `wgit` gem which fixes a bug in `crawl_site` and adds support for IRI's (including umlauts).
### Fixed
- Bug where an error from the executable wasn't being rescued. Now all errors are presenting to the user in a clean manner (without the stack trace).
---

@frederickjh can you please retest your scenarios and update this issue? Thanks.

**Comment by michaeltelford** [comment]
Version 0.9.0 has been released and contains the following changes:

## v0.9.0
### Added
- The `version` command to the executable.
- The `--threads` aka `-t` option to the executable's `crawl` command to control crawl speed vs. resource usage.
### Changed/Removed
- Changed the default number of maximum threads for a recursive crawl from 30 to 100. Users will see a speed boost with increased resource usage as a result. This is configurable using the new `crawl` command option e.g. `--threads 30`.
### Fixed
- Several bugs by updating the `wgit` dependancy including the 'Invalid URL' error.
- A bug in the report logic causing an incorrect link count.
---

@frederickjh This should address the issues in the last release, can you retest and confirm the status of this issue please?

**Comment by frederickjh** [comment]
The logic to not re-crawl links seems to be working. The number of links checked dropped from 17 to 15 as two links were present twice on the page once as absolute links and once as relative links.

**Comment by frederickjh** [comment]
I also did not receive any messages from the server about the load going over 2 while the checks were being run.

**Comment by michaeltelford** [comment]
Hi Frederick,

Good to hear, thanks!

Michael

**Comment by frederickjh** [comment]
I forgot to say these test were run without adjusting the rate limiting, just using the defaults on a Intel(R) Pentium(R) 4 CPU 2.80GHz.

**Comment by frederickjh** [comment]
The newest release was tested on a server with only a Intel(R) Pentium(R) 4 CPU 2.80GHz. Before the system monitoring would send out emails that the system load had gone over 2 when running checks on a site. With the new version no emails were received. CPU 1 minute load was monitored during the check and it got as high as 1.33. CPU percentage for the broken_link_finder parent process varied from 50% to 87%.
I consider these to be good results. I am therefore closing.
