### ISSUE TITLE
Links in external page show in the broken links report - URI::InvalidURIError - URI must be ascii only

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#5]
In testing on one site I found that one page on the site being check was redirecting to an external page. broken_link_finder reported broken links in the external page too.

The thing that clued me in to it was some of the link were broken CSS and JS script files that we do not have on the site that was being tested.

@michaeltelford I will send an email with more details on the sites and pages in question  for you to be able to test yourself.

**Comment by frederickjh** [comment]
After having checked these relative links that were reported broken, I found that yes they do not exist on page on the site being checked but they do exist on the page that it was redirecting to.

**Comment by frederickjh** [comment]
The site that was being redirected to has an umlaut (ÜÖÄäöü) in the URI. Running broken_link_finder directly on the site returned this error:
```
$ broken_link_finder crawl --sort-by-link --no-recursive  https://www.übersetzer.com
Traceback (most recent call last):
```
`**<snip>**`
```
3: from /home/username/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/common.rb:737:in `URI'
2: from /home/username/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
1: from /home/username/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
/home/username/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "https://www.\u00FCbersetzer.com" (URI::InvalidURIError)
```

Umlauts are valid in URIs today, but it looks like broken_link_finder or one of its dependencies cannot handle them.

**Comment by frederickjh** [comment]
[stackoverflow.com - How to use umlauts with ruby's URI library](https://stackoverflow.com/questions/10519591/how-to-use-umlauts-with-rubys-uri-library)

**Comment by michaeltelford** [comment]
Thanks for raising the issue @frederickjh. There are 3 separate issues described here:

1) The executable shouldn't be erroring with a full stack trace. The errors should be better handled. This will be fixed in the next release.

2) `crawl_site` shouldn't be crawling pages outside of the main website. The redirect is key to the issue and will be fixed in the next release.

3) Umlauts (ÜÖÄäöü) (and other non ASCII based characters) aren't currently supported but should be. I will look into this and hopefully have a fix in the next release.

**Comment by michaeltelford** [comment]
OK, `broken_link_finder 0.8.1` should resolve the issues raised above. Here are the details for this version from the `CHANGELOG`:

## v0.8.1
### Added
- Logic to prevent re-crawling links for more efficiency. Users should see a substantial speed boost when crawling large sites with repeated links. This should also somewhat help prevent servers from dropping requests due to suspected DOS attacks.
### Changed/Removed
- Updated the `wgit` gem which fixes a bug in `crawl_site` and adds support for IRI's (including umlauts).
### Fixed
- Bug where an error from the executable wasn't being rescued. Now all errors are presenting to the user in a clean manner (without the stack trace).
---

@frederickjh can you please retest your scenarios and update this issue? Thanks.

**Comment by michaeltelford** [comment]
Version 0.9.0 has been released and contains the following changes:

## v0.9.0
### Added
- The `version` command to the executable.
- The `--threads` aka `-t` option to the executable's `crawl` command to control crawl speed vs. resource usage.
### Changed/Removed
- Changed the default number of maximum threads for a recursive crawl from 30 to 100. Users will see a speed boost with increased resource usage as a result. This is configurable using the new `crawl` command option e.g. `--threads 30`.
### Fixed
- Several bugs by updating the `wgit` dependancy including the 'Invalid URL' error.
- A bug in the report logic causing an incorrect link count.
---

@frederickjh This should address the issues in the last release, can you retest and confirm the status of this issue please?

**Comment by frederickjh** [comment]
> 2. `crawl_site` shouldn't be crawling pages outside of the main website. The redirect is key to the issue and will be fixed in the next release.

I just re-read this. I think I understand what you are saying here in that it should not crawl pages outside the main site. However it should check links to external pages.

What I found happening was relative links in an external page were being rendered not with the domain  name of the website there were actually on, but with the domain name of the original site being checked.

**Comment by michaeltelford** [comment]
Hi Frederick,

Yes, links to external sites are checked for breakages. The fix affects internal page links that redirect to external sites, previously they were crawled as part of the original domain/site. This should all be fixed in the latest release.

Michael

**Comment by frederickjh** [comment]
In my tests, this is now functioning correctly, therefore closing issue.
