### ISSUE TITLE
Feature Request - Support a HTML report format

### ISSUE THREAD

**Issue by frederickjh** [michaeltelford/broken_link_finder#6]
Currently with the text based email format only the absolute links in the email reports get made into clickable links by some email clients.

Changing the email format to HTML would mean that both absolute and relative links could be formatted so that they are clickable links.

**Comment by michaeltelford** [comment]
Yes, this makes sense. 

In future versions, a `--html` command-line flag will exist. Setting this flag will output an HTML report containing clickable well-formed links.

**Comment by michaeltelford** [comment]
This feature has been implemented and will be available via a `--html` flag in the next release. I will close this issue when the next release is out (within the next week or so).

**Comment by michaeltelford** [comment]
This issue is fixed in the latest release. From the `CHANGELOG`:

## v0.10.0
### Added
- A `--html` flag to the `crawl` executable command which produces a HTML report (instead of text).
- Added a 'retry' mechanism for any broken links found. This is essentially a verification step before generating a report.
- `Finder#crawl_stats` for info such as crawl duration, total links crawled etc.
### Changed/Removed
- The API has changed somewhat. See the [docs](https://www.rubydoc.info/gems/broken_link_finder) for the up to date code signatures if you're using `broken_link_finder` outside of its executable.
### Fixed
- ...
---

FYI @frederickjh ^^^

**Comment by frederickjh** [comment]
@michaeltelford Thanks for implementing this. Everything seems to work well. The only thing I noticed that does not get converted to HTML is the website url in the crawl stats at the top of the report returned.

**Comment by michaeltelford** [comment]
Ok @frederickjh, I will add this point to an existing issue around the reporting. Thanks for pointing this out.
